name: MEAN App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Step 4: Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Step 5: Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm run build --prod

      # Step 6: Build Docker Images
      - name: Build Docker Images
        run: docker-compose build

      # Step 7: Run containers (optional)
      - name: Run Containers
        run: docker-compose up -d
