name: MEAN App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build --prod

      # ✅ FIXED HERE
      - name: Build Docker Images
        run: docker compose build

      - name: Run Containers
        run: docker compose up -d
